README.md
Mullvad security check url moved...
=> Mullvad security check url moved

src/main.rs
=> auto detect protocol when using custom config

Cargo.toml, src/exec.rs, src/list.rs, src/list_configs.rs, src/main.rs, src/netns.rs, src/openconnect.rs, src/sync.rs, src/util/mod.rs, src/vpn.rs
=> Add preliminary Cisco OpenConnect support.

Cargo.toml, src/main.rs, src/netns.rs, src/pulseaudio.rs
Check pactl to set PULSE_SERVER for PulseAudio support
=> Add PulseAudio support

Cargo.toml, src/util/mod.rs
=> Fix config file permissions so not world readable

Cargo.toml, README.md, src/exec.rs, src/netns.rs, src/wireguard.rs
Fixes issue #68 
Bump version to also release PR #67
=> Fix Wireguard DNS override

Cargo.toml, README.md, USERGUIDE.md, src/exec.rs, src/main.rs
TOML file located in `~/.config/vopono/config.toml`
Example contents:
```
firewall = "NfTables"
provider = "Mullvad"
protocol = "Wireguard"
server = "us"
```
=> Add vopono config file support

Cargo.toml, USERGUIDE.md, src/exec.rs, src/netns.rs
Also add dns argument to config file settings
See #71 
TODO: More testing.
=> Add VOPONO_NS environment variable for scripts

Cargo.toml, README.md, USERGUIDE.md, src/application_wrapper.rs, src/args.rs, src/dns_config.rs, src/exec.rs, src/list_configs.rs, src/main.rs, src/netns.rs, src/network_interface.rs, src/openconnect.rs, src/openfortivpn.rs, src/openvpn.rs, src/shadowsocks.rs, src/sync.rs, src/util/mod.rs, src/vpn.rs, src/wireguard.rs
- Fixed issue where root's XDG_CONFIG settings would take precedence over sudo user
- Added OpenFortiVPN support with route and DNS handling
- Added more debug info to many command executions and file I/O
=> Add OpenFortiVPN support and better logging

Cargo.toml, src/veth_pair.rs
=> Fix NetworkManager config path edge case

Cargo.toml, src/openvpn.rs
=> Increase logfile buffer size for OpenVPN

Cargo.toml, src/openvpn.rs
=> Filter out Windows-specific OpenVPN command

Cargo.toml, src/exec.rs, src/main.rs, src/network_interface.rs, src/util/mod.rs
And modify checks to get config directory to work-around case where root has $HOME set bur the sudo_user does not.
See issues #116 and #115
=> Use hash for custom provider name

src/args.rs, src/main.rs, src/util/mod.rs
Add sudo askpass flag to vopono #87
=> add sudo askpass flag

Cargo.toml, README.md, USERGUIDE.md, src/providers/airvpn/mod.rs, src/providers/airvpn/openvpn.rs
=> Update docs for AirVPN support

USERGUIDE.md
explicitly state how to use custom ovpn configuration files which require a username and password
=> custom provider auth

src/openvpn.rs
This is related to #162 and #163. It is the firewall setup that I am using without any issues (with OpenVPN and IPv4 only). There is no new code as you can see. I only enabled/removed existing code. I have no idea if this would also work in general though. Maybe this shouldn't be hard coded, but controlled by options or other logic instead.
=> Changes to remote's and DNS firewall rules

src/exec.rs, vopono_core/src/network/netns.rs, vopono_core/src/util/mod.rs, vopono_core/src/util/open_hosts.rs
This code allow to use the open_host feature after fixing the holes in the kill switch #167. This should also allow #159 with activated kill switch.
=> Allow open_hosts with killswitch

Cargo.toml, src/args.rs, src/cli_client.rs, src/exec.rs, src/list_configs.rs, src/main.rs, src/sync.rs, vopono_core/Cargo.toml, vopono_core/src/config/providers/airvpn/openvpn.rs, vopono_core/src/config/providers/azirevpn/mod.rs, vopono_core/src/config/providers/azirevpn/openvpn.rs, vopono_core/src/config/providers/azirevpn/wireguard.rs, vopono_core/src/config/providers/hma/openvpn.rs, vopono_core/src/config/providers/ivpn/openvpn.rs, vopono_core/src/config/providers/ivpn/wireguard.rs, vopono_core/src/config/providers/mod.rs, vopono_core/src/config/providers/mozilla/mod.rs, vopono_core/src/config/providers/mozilla/wireguard.rs, vopono_core/src/config/providers/mullvad/mod.rs, vopono_core/src/config/providers/mullvad/openvpn.rs, vopono_core/src/config/providers/mullvad/wireguard.rs, vopono_core/src/config/providers/nordvpn/openvpn.rs, vopono_core/src/config/providers/pia/openvpn.rs, vopono_core/src/config/providers/protonvpn/openvpn.rs, vopono_core/src/config/providers/tigervpn/mod.rs, vopono_core/src/config/vpn.rs, vopono_core/src/network/firewall.rs, vopono_core/src/network/netns.rs, vopono_core/src/network/openconnect.rs
- TODO: Fix trait object issues for UiClient trait
Plan is to separate out CLI code in to the client only, so `vopono_core` is interface agnostic.
Necessary for future GUI work.
=> Refactor dialoguer code into cli_client - WIP

Cargo.toml, README.md, USERGUIDE.md, vopono_core/Cargo.toml, vopono_core/src/config/providers/mullvad/wireguard.rs
Changelog:
- Added Wireguard support for PrivateInternetAccess - see issue #9 and PR #183 - thanks to @mobad 
- Updated dependencies
=> vopono 0.10.2

Cargo.toml, vopono_core/Cargo.toml, vopono_core/src/network/netns.rs
=> Fix wireguard_preup issue for Wireguard custom providers

Cargo.toml, vopono_core/Cargo.toml, vopono_core/src/util/wireguard.rs
=> vopono v0.10.5 - fix error handling in basic_tcp_proxy

USERGUIDE.md
NordVPN now requires user credentials to be generated
=> Update USERGUIDE.md (NordVPN)

src/exec.rs, src/main.rs, vopono_core/Cargo.toml, vopono_core/src/network/netns.rs, vopono_core/src/network/openvpn.rs
- Check for up / down scripts in custom OpenVPN config and alert if present
- Print full OpenVPN output when using `--verbose`
=> Improve OpenVPN logging when verbose

README.md
Thanks for this wonderful tool!
It's available here:
https://packages.gentoo.org/packages/net-vpn/vopono
=> README.md: vopono is available in Gentoo, add installation instruction

vopono_core/src/config/providers/protonvpn/openvpn.rs
Is now better at handling whitespace and trailing characters
Addresses Issue #301
=> Switch ProtonVPN AUTH cookie parsing to Regex

vopono_core/Cargo.toml, vopono_core/src/network/trojan/get_cert.rs
Avoid OpenSSL issues on CI machines
=> Switch get_cert to rustls

src/exec.rs, vopono_core/src/network/application_wrapper.rs, vopono_core/src/network/dns_config.rs, vopono_core/src/network/netns.rs, vopono_core/src/network/openvpn.rs, vopono_core/src/network/port_forwarding/natpmpc.rs, vopono_core/src/network/wireguard.rs, vopono_core/src/util/env_vars.rs, vopono_core/src/util/open_ports.rs
=> Fix creation of nftables tables and chains

Cargo.toml, src/exec.rs, vopono_core/Cargo.toml, vopono_core/src/config/providers/azirevpn/wireguard.rs, vopono_core/src/config/providers/ivpn/wireguard.rs, vopono_core/src/config/providers/mozilla/wireguard.rs, vopono_core/src/config/providers/mullvad/wireguard.rs, vopono_core/src/config/providers/pia/wireguard.rs, vopono_core/src/network/dns_config.rs, vopono_core/src/network/host_masquerade.rs, vopono_core/src/network/mod.rs, vopono_core/src/network/netns.rs, vopono_core/src/network/trojan/trojan_config.rs, vopono_core/src/network/trojan/trojan_exec.rs, vopono_core/src/network/wireguard.rs, vopono_core/src/network/wireguard_config.rs, vopono_core/src/util/env_vars.rs, vopono_core/src/util/open_hosts.rs, vopono_core/src/util/open_ports.rs
Fixes issues with IPv6 endpoints and DNS servers for Wireguard
Should fix issue #181
=> IPv6 improvements

Cargo.toml, src/exec.rs, src/main.rs, vopono_core/Cargo.toml, vopono_core/src/config/providers/ivpn/wireguard.rs, vopono_core/src/config/providers/mozilla/mod.rs, vopono_core/src/network/openvpn.rs, vopono_core/src/network/port_forwarding/azirevpn.rs, vopono_core/src/util/mod.rs
=> vopono now returns application exit code
