src/openvpn.rs

Fixes #31.
Previously, when passing a relative path not proceded by `.` or `..` to `--custom`, it would fail with `No such file or directory`, since the working directory was not properly resolved.
This canonicalizes all relative paths first, turning them into absolute paths. This means that the working directory can always be resolved, and avoids all the issues with `parent()` mentioned in rust-lang/rust#36861.
The path to the config file is also canonicalized, since this enables using config files in different directories.
For example, previously for `--config ./test/foo.conf`, openvpn would be executed in the `./test/` directory, but passed `./test/foo.conf`, which made openvpn fail/hang because the file did not exist.
Now,  openvpn is executed in `/absolute/path/test/`, and passed …

Custom provider: Properly handle relative paths

---

.github/workflows/pr.yml
.github/workflows/rust.yml
Cargo.toml
README.md
src/application_wrapper.rs
src/args.rs
src/exec.rs
src/main.rs
src/netns.rs
src/openvpn.rs
src/util/mod.rs
src/util/open_ports.rs
src/wireguard.rs

Resolves #30 #28 #24 
Somewhat resolves #29 but not perfectly for transmission-daemon as it spawns a new process (without the original being the parent). This also means the transmission-daemon doesn't get killed even after SIGINT is sent :crying_cat_face:

Add port forwarding and TCP proxying support for daemons/servers

---

Cargo.toml
src/exec.rs
src/util/mod.rs

When executing an interactive shell (such as `python` or similar), it is commonly necessary to communicate with the program using CTRL+C (for example, to terminate a long running action within it). Additionally, some long-running actions (such as `ping`) expect to be terminated using CTRL-C.
However, when running inside vopono, this kills vopono as well, thus not running any cleanup and taking the shell with it.
This PR catches all SIGINT signals during `exec` (they are automatically sent to the application as well, since it is in the same process group). This allows to child to respond to the signal as expected (handling in case of `python`, terminating in case of `ping`) and ensures graceful shutdown as vopono only exits after the child has exited.

Handle SIGINT gracefully

---

Cargo.toml
src/providers/mod.rs
src/providers/nordvpn/mod.rs
src/providers/nordvpn/openvpn.rs

Adding NordVPN to the list of providers. Note that this is only supported via OpenVPN. For wireguard, they've built an extra layer on top of it called [NordLynx](https://nordvpn.com/blog/nordlynx-protocol-wireguard/), which is intended to avoid having to store identifiable data on their servers. Unfortunately, they don't currently have any documentation on how to set up wireguard to connect to NordLynx. It's set up in their Linux client, but I don't know enough about wireguard config to be able to dig further to try to find out more details.

Add NordVPN as provider

---

Cargo.toml
src/providers/nordvpn/openvpn.rs

This should fix #62, stripping the directory name from the paths in the zip file ("ovpn_tcp" and "ovpn_udp"). It would be good to get someone to confirm if possible (@mobad?), but it's working on my end.

Strip directory from NordVPN filenames

---

src/providers/protonvpn/openvpn.rs

For the Plus tier of ProtonVPN, the user has the ability to select servers tailored for p2p or Tor networks. However, forewarning: this is my first exposure to the Rust language. The addition seemed fairly simple.

add choice to pick certain features

---

Cargo.toml
USERGUIDE.md
src/args.rs
src/exec.rs
src/netns.rs
src/util/mod.rs

See issue #71 
Also modified prefix for configs so that one can provide the precise config file name itself, in order to use a specific config (i.e. specific Mullvad US city for example) in the vopono config file.

Add ability to provide PostUp and PreDown scripts

---

Cargo.toml
src/netns.rs
src/openconnect.rs
src/openfortivpn.rs
src/openvpn.rs
src/providers/ivpn/wireguard.rs
src/providers/mozilla/wireguard.rs
src/providers/mullvad/wireguard.rs
src/providers/nordvpn/openvpn.rs
src/veth_pair.rs
src/wireguard.rs

Changes:
- Now check NetworkManager is actually running rather than just for the
existence of the configuration file, before trying to apply
NetworkManager config changes.
- Failure to apply NetworkManager config changes now results in a
warning instead of an error.
- Added detection of systemd's firewalld to permit the veth device
needed for the network namespace (much like with Network Manager
previously).
- Added "recommends" dependencies to Debian dpkg with cargo-deb

Improve NetworkManager, firewalld support

---

Cargo.toml
README.md
src/exec.rs
src/providers/airvpn/mod.rs
src/providers/airvpn/openvpn.rs
src/providers/azirevpn/openvpn.rs
src/providers/hma/openvpn.rs
src/providers/ivpn/openvpn.rs
src/providers/mod.rs
src/providers/mullvad/openvpn.rs
src/providers/nordvpn/openvpn.rs
src/providers/pia/openvpn.rs
src/providers/protonvpn/openvpn.rs
src/providers/tigervpn/mod.rs
src/vpn.rs

Code for the provider AirVPN. I have adapted the OpenVPN API accordingly so that an auth file is now optional. Unfortunately I have little experience with rust and the implementation will probably not be optimal. Therefore feel free to adapt it to your needs.
I don't have check if the changes break OpenVPN with auth file!

Add AirVPN Provider with optional auth file

---

src/wireguard.rs

This change improves the regexp matching Wireguard config key/value pairs to allow spaces within the value.
It also improves the error message in the case where parsing the transformed config fails.
I don't think this regexp-based approach can actually be reliable (for one thing the `PostUp` and similar config keys could contain double quotes) but these changes should make failure less likely in the common case.
Closes #132

Make conversion from Wireguard config format to TOML more robust and improve error output.

---

src/exec.rs

**Note**: I made this change without really understanding the rest of the code or testing with non-custom providers. It  compiles appears to work in this case. It seems like the simple/obvious solution but I'm not 100% sure it's correct. Please review before merging.
Closes #134

Use custom_config variable to verify custom config is specified rather than only looking in commandline.

---

Cargo.toml
USERGUIDE.md
src/args.rs
src/exec.rs
src/firewall.rs
src/list_configs.rs
src/main.rs
src/openconnect.rs
src/openfortivpn.rs
src/openvpn.rs
src/providers/airvpn/openvpn.rs
src/providers/azirevpn/mod.rs
src/providers/hma/openvpn.rs
src/providers/ivpn/wireguard.rs
src/providers/mod.rs
src/providers/mozilla/wireguard.rs
src/providers/mullvad/wireguard.rs
src/providers/nordvpn/openvpn.rs
src/sync.rs
src/vpn.rs
src/wireguard.rs

StructOpt is removed as a dependency
Also make DNS setting in Wireguard config optional
And added note regarding AllowedIPs in Wireguard config needing to
allow all IPs as discussed in PR #135 
Closes issue #125

Switch to Clap v3

---

src/args.rs
src/dns_config.rs
src/exec.rs
src/netns.rs
src/openfortivpn.rs
src/wireguard.rs

I would like to use vopono in combination with a web browser. I have not found a safe way to integrate my locally hosted services like vaultwarden for password management and webdav to synchronize the bookmarks in the current vopono version. Therefore I have added two parameters to vopono `exec` command:
- `--open-hosts <OPEN_HOSTS>`: List of host ip's to open on network namespace (comma separated)
- `--hosts <HOSTS_ENTRIES>`:  List of `/etc/hosts` entries for the network namespace (e.g. "10.0.1.10             webdav.server01.lan","10.0.1.10 vaultwarden.server01.lan"). This acts mainly as a dns rewrite/override for an local domain.

Feature to allow the access to local hosted services

---

Cargo.toml
USERGUIDE.md
src/dns_config.rs
src/exec.rs

- Updated dependencies
- Added warning when there are multiple active network interfaces (issue #149 )
- Sets 644 permissions for netns configs explicitly ( issue #156  )
- Added Jackett example to user guide

vopono 0.9.1

---

src/exec.rs
src/netns.rs
src/openconnect.rs

- Openconnect will now use the custom config provided to Vopono.
- Openconnect is now able to authenticate with the provided password
- It's not possible to provide a username via Vopono to Openconnect. This is due to there not being a simple optional way to provide it and the username clashing with the one provided in the openconnect-config.
- Openconnect will use the optionally provided server, or the server from its custom config. If both are provided openconnect will fail.
An example minimal openconnect.conf which can be provided as a custom config:
with server:
```
server = vpn.example.com
user = user
```
without server:
```
user = user
```
Generally you can add all command-line-arguments from openconnect. E.g. my tested VPN-config would look like this:
```
server = vpn.example.com …
```

fix(openconnect): let openconnect use its config

---

vopono_core/src/network/netns.rs

Truncate source and dest interface at the beginning to make name clashes less likely.
This solves an issue where different vpn configurations result in the same device name.

Truncate source and dest interface at the beginning

---

.github/workflows/rust.yml
src/args.rs
src/exec.rs
vopono_core/src/network/application_wrapper.rs
vopono_core/src/network/netns.rs
vopono_core/src/network/openconnect.rs
vopono_core/src/network/openfortivpn.rs
vopono_core/src/network/openvpn.rs
vopono_core/src/network/shadowsocks.rs
vopono_core/src/network/wireguard.rs
vopono_core/src/util/mod.rs

Fixes:
- #174  - now only the OpenConnect invocation takes over stdin itself, bash works again :slightly_smiling_face: 
- #175 - "dead" namespaces will not be cleaned if there are PIDs running - however this does not apply to the vopono namespace cleaning itself up - i.e. if you use the same network namespace and vopono with different users at the same time then closing either one would still clean up the network namespace.
- #169 - aarch64 binaries and deb added to Github action
- #172 and #173 - UI code has been refactored into UIClient trait and clap ArgEnum enums are wrapped with the WrappedArg struct in `args.rs`
- #159 - with the `--allow-host-access` flag to access the local host (note the host IP address will likely be `10.200.1.1` (or `10.200.x.1` when running multiple vopono …

vopono 0.10.1

---

src/args.rs
src/exec.rs
vopono_core/src/network/application_wrapper.rs
vopono_core/src/network/netns.rs
vopono_core/src/network/openconnect.rs
vopono_core/src/network/openfortivpn.rs
vopono_core/src/network/openvpn.rs
vopono_core/src/network/shadowsocks.rs

```
$ cargo run -- exec -c Wireguard --custom mullvad-de11.conf -u deluge --postup 'id' --predown 'id' id
[...]
uid=993(deluge) gid=993(deluge) groups=993(deluge)
uid=993(deluge) gid=993(deluge) groups=993(deluge)
uid=993(deluge) gid=993(deluge) groups=993(deluge)
[...]
$ cargo run -- exec -c Wireguard --custom mullvad-de11.conf -u deluge -g users --postup 'id' --predown 'id' id
[...]
uid=993(deluge) gid=100(users) groups=100(users),993(deluge)
uid=993(deluge) gid=100(users) groups=100(users),993(deluge)
uid=993(deluge) gid=100(users) groups=100(users),993(deluge)
[...]
$ cargo run -- exec -c Wireguard --custom mullvad-de11.conf -w /tmp pwd
[...]
/tmp
[...]
$ cargo run -- exec -c Wireguard --custom mullvad-de11.conf pwd
[...]
/home/hashworks/Documents/Projects/Rust/vopono
[...]
```

Add ability to set group and working directory for command

---

vopono_core/src/network/wireguard.rs

Fix wiregaurd config parser such that deserializer is called correctly.
To reproduce the bug use a custom wiregaurd config with a DNS name in the `Peer.Endpoint` section. This MR corrects the bug by invoking the deserializer which in turn calls `toSocket`
https://doc.rust-lang.org/std/net/trait.ToSocketAddrs.html

Allow DNS Names in Custom Wiregaurd Configs

---

vopono_core/src/config/providers/protonvpn/openvpn.rs

ProtonVPN deprecated the Basic plan sometime ago.

Remove deprecated ProtonVPN Basic plan

---

vopono_core/src/network/openvpn.rs

Fixes #212.
I'm not sure if this is the best approach, or if it's better to switch to a dependency (eg. something like https://crates.io/crates/ovpnfile) that is built to parse ovpn files. There might be other edge cases that I am not aware of.

openvpn: ignore comments in ovpn config file

---

src/exec.rs
vopono_core/src/config/providers/airvpn/mod.rs
vopono_core/src/config/providers/azirevpn/mod.rs
vopono_core/src/config/providers/hma/mod.rs
vopono_core/src/config/providers/ivpn/mod.rs
vopono_core/src/config/providers/mod.rs
vopono_core/src/config/providers/mozilla/mod.rs
vopono_core/src/config/providers/mullvad/mod.rs
vopono_core/src/config/providers/nordvpn/mod.rs
vopono_core/src/config/providers/pia/mod.rs
vopono_core/src/config/providers/protonvpn/mod.rs
vopono_core/src/config/providers/tigervpn/mod.rs
vopono_core/src/network/netns.rs

The generation of netns/veth names is changed as discussed in #177.
This makes the names usable in firewall rules while still limiting their length.
If necessary the server/config-name is converted to a 7-character hash.

Improved netns name generation

---

vopono_core/src/network/wireguard.rs

This fixes #216 by using a split on '=' instead of whitespace to parse keys when filtering Wireguard config keys. I also took the liberty of swapping the denylist to an allowlist of the valid wireguard config keys from the manpage.

Fix wireguard config filtering for configs without whitespace.

---

src/exec.rs
vopono_core/src/util/pulseaudio.rs

Also strip out '-' from network namespace name even when under 7 characters to avoid syntax errors
Fixes #219 and ensures #218 doesn't occur even for short server names.
Note we could use `serde_json` instead but it seemed overkill for one field (although note we do it use it in `vopono sync` anyway).

Fix pactl parsing when in non-English language

---

Cargo.toml
README.md
USERGUIDE.md
vopono_core/Cargo.toml
vopono_core/src/config/providers/mod.rs
vopono_core/src/config/providers/protonvpn/openvpn.rs
vopono_core/src/config/providers/ui.rs
vopono_core/src/config/vpn.rs

ProtonVPN now requires the user to be authenticated to access the configuration files.
We now request that the user log in via their browser and then copy the value of the `AUTH-` cookie.
Note the `Feature` specification for filtering for Tor / Torrent optimised servers has been removed from ProtonVPN's configuration page, and so is removed here too.
Also note that for SecureCore configs, the first name in the filename is the output node country, as this is probably the most useful for filtering.
Fixes issue #201

Fix sync for ProtonVPN OpenVPN configs

---

README.md
USERGUIDE.md
src/exec.rs
src/list_configs.rs
src/sync.rs
vopono_core/src/config/providers/mod.rs
vopono_core/src/config/providers/warp/mod.rs
vopono_core/src/config/vpn.rs
vopono_core/src/network/mod.rs
vopono_core/src/network/netns.rs
vopono_core/src/network/warp.rs

Add basic support for Cloudflare Warp
TODO: Add killswitch support:
https://developers.cloudflare.com/cloudflare-one/connections/connect-devices/warp/deployment/firewall/
Note not tested with Teams features, etc.
Addresses issue #235

Add Cloudflare Warp support

---

USERGUIDE.md
src/args.rs
src/exec.rs
vopono_core/src/network/shadowsocks.rs
vopono_core/src/util/mod.rs

Add create-netns-only argument for debugging + firejail usage

---

vopono_core/src/config/providers/mozilla/wireguard.rs
vopono_core/src/config/providers/mullvad/mod.rs
vopono_core/src/config/providers/mullvad/openvpn.rs
vopono_core/src/config/providers/mullvad/wireguard.rs

Mullvad has unfortunately deprecated the API for handling Wireguard keys See issue #243  - https://github.com/jamesmcm/vopono/issues/243
This change removes that code and relies on the user uploading their Wireguard public key and recording the return IPv4 and IPv6 ranges directly.

Remove Mullvad API usage for Wireguard keys

---

Cargo.toml
src/exec.rs
vopono_core/Cargo.toml
vopono_core/src/config/providers/mozilla/wireguard.rs
vopono_core/src/config/providers/mullvad/mod.rs
vopono_core/src/config/providers/mullvad/wireguard.rs
vopono_core/src/util/mod.rs

Adds support for new API for Wireguard device management so we can generate and add Wireguard keys directly when syncing
See issue #243 and PR #244

Re-add Mullvad Wireguard device management

---

.gitignore
Cargo.toml
README.md
USERGUIDE.md
src/args.rs
src/exec.rs
vopono_core/Cargo.toml
vopono_core/src/network/natpmpc.rs
vopono_core/src/network/piapf.rs

Fixes port forwarding when using Wireguard with ProtonVPN as custom provider config files, e.g.:
```bash
$ vopono -v exec --custom ~/hostname-RO-9.conf --protocol wireguard --provider custom --custom-port-forwarding protonvpn --port-forwarding-callback ./print_first_arg.sh firefox-developer-edition
```
Fixes Wireguard part of issue #247

Fix port forwarding for custom ProtonVPN WG config

---

src/exec.rs
vopono_core/src/network/application_wrapper.rs
vopono_core/src/network/mod.rs
vopono_core/src/network/port_forwarding/mod.rs
vopono_core/src/network/port_forwarding/natpmpc.rs
vopono_core/src/network/port_forwarding/piapf.rs

For ProtonVPN and PrivateInternetAccess port forwarding which require regularly re-acquiring the port in another thread

Refactor shared code in port forwarding into traits

---

Cargo.toml
src/args.rs
src/args_config.rs
src/exec.rs
src/list_configs.rs
src/main.rs
src/sync.rs
vopono_core/Cargo.toml
vopono_core/src/config/providers/mod.rs
vopono_core/src/config/vpn.rs
vopono_core/src/network/netns.rs
vopono_core/src/util/mod.rs

- Add None provider and protocol for solely  creating network-ready network namespace with no VPN service
- Add shell path expansion to path arguments (e.g. you can use ~ in custom config path)
- Refactor how CLI arguments are parsed using macro_rules
- Now all CLI args except `application` can be set in the vopono config TOML too

Add None provider, path expansion, refactoring

---

Cargo.toml
src/args_config.rs
src/list.rs
vopono_core/Cargo.toml

Fixes issue #254 
Interface must be parsed as string explicitly and then converted if present

Fix network interface parsing from config file

---

USERGUIDE.md

Clarify how to use multiple -f flags for multiple ports in a single namespace
---------------------------------------
I found this confusing resulting in opening an issue yesterday. This documentation change makes it explicit in how to use this feature correctly

Clarify multiple port accessibility

---

README.md

I've used vopono several times but somehow I've missed that it can be used with your own OpenVPN server
I think putting something like a "Self" provider in the table would make it a lot more clear. Open to edits on the specific language but I definitely think it should be in the table somewhere because some people only look at tables

docs: make it more clear that one can self host

---

Cargo.toml
USERGUIDE.md
src/args.rs
src/args_config.rs
src/exec.rs
src/main.rs
src/sync.rs
vopono_core/Cargo.toml
vopono_core/src/config/providers/azirevpn/mod.rs
vopono_core/src/config/providers/azirevpn/openvpn.rs
vopono_core/src/config/providers/azirevpn/wireguard.rs
vopono_core/src/config/providers/mod.rs
vopono_core/src/config/providers/mullvad/openvpn.rs
vopono_core/src/config/providers/nordvpn/openvpn.rs
vopono_core/src/config/providers/pia/openvpn.rs
vopono_core/src/config/providers/pia/wireguard.rs
vopono_core/src/config/vpn.rs
vopono_core/src/network/application_wrapper.rs
vopono_core/src/network/dns_config.rs
vopono_core/src/network/openfortivpn.rs
vopono_core/src/network/openvpn.rs
vopono_core/src/network/port_forwarding/azirevpn.rs
vopono_core/src/network/port_forwarding/mod.rs
vopono_core/src/network/wireguard.rs
vopono_core/src/util/country_map.rs
vopono_core/src/util/mod.rs
vopono_core/src/util/wireguard.rs

So far:
- Fixes AzireVPN support for Wireguard and OpenVPN in `vopono sync` - Issue #269 
- Adds support for Wireguard port forwarding for AzireVPN
- Adds support for replacing keys for existing device when syncing with AzireVPN
- No longer removes OpenVPN auth file on authentication failure (due to intermittent NordVPN authentication issues) - Issue #288 
- Censors private key in logs - Issue #274 
- Removed references to IVPN port forwarding as it is no longer offered - Issue #285 
- Fixed `RUST_LOG` env var parsing and added `--silent` flag to silence application too - Issue #280

Vopono v0.10.11

---

README.md
USERGUIDE.md
vopono_core/Cargo.toml
vopono_core/src/network/warp.rs

Fixes #235 (original PR was #237 )
Fix Cloudflare Warp by re-directing the write to /etc/resolv.conf to the netns resolv.conf at /etc/netns/vo_wp_warp/resolv.conf
This is very hacky, but it works.
Note it is also necessary to disable Warp's connectivity check: i.e. a new user should first run the following on the host, outside of vopono:
```
$ sudo warp-svc
$ sudo warp-cli registration new
$ sudo warp-cli connect
$ sudo warp-cli debug connectivity-check disable
```
And then kill warp-svc directly e.g. with ctrl+C

Fix Cloudflare Warp

---

vopono_core/src/config/providers/azirevpn/wireguard.rs
vopono_core/src/config/providers/ivpn/wireguard.rs
vopono_core/src/config/providers/mozilla/wireguard.rs
vopono_core/src/config/providers/mullvad/wireguard.rs
vopono_core/src/config/providers/pia/wireguard.rs
vopono_core/src/network/wireguard.rs

Default is 1420 otherwise.
Note atm we set 1420 in all sync-generated configs, this should be swapped for the actual provider-preferred value when possible.
Addresses part of issue #306

Read MTU from Wireguard config when present

---

src/exec.rs
vopono_core/src/network/application_wrapper.rs
vopono_core/src/util/env_vars.rs
vopono_core/src/util/mod.rs

The change to set env vars for each spawned command separately to avoid the now unsafe global set_env accidentally meant they were not set for the application run by vopono itself in the netns, and so were not present for scripts there.

Fix regression where vopono env vars not set

---

vopono_core/src/config/providers/mullvad/openvpn.rs
vopono_core/src/config/providers/mullvad/wireguard.rs

Use Mullvad's DNS with Wireguard

Set Mullvad DNS correctly for Wireguard

---

vopono_core/src/config/providers/azirevpn/mod.rs
vopono_core/src/config/providers/azirevpn/wireguard.rs
vopono_core/src/network/host_masquerade.rs
vopono_core/src/network/netns.rs
vopono_core/src/network/wireguard.rs
vopono_core/src/network/wireguard_config.rs
vopono_core/src/util/env_vars.rs

Fixes new API calls parsing added in PR #305 for issue #294 for `vopono sync`
Note atm we ignore devices with null names which can happen if their access tokens have been deleted separately.

Fix AzireVPN parsing

---

Cargo.toml
vopono_core/Cargo.toml
vopono_core/src/config/providers/mozilla/mod.rs
vopono_core/src/config/providers/mullvad/openvpn.rs
vopono_core/src/network/shadowsocks.rs
vopono_core/src/network/trojan/get_cert.rs
vopono_core/src/util/mod.rs
vopono_core/src/util/wireguard.rs

Upgrades rand and x25519-dalek - note atm we have to use a pre-release version for the latter.

Rand and x25519-dalek upgrade
